spring:
  datasource:
    #    url: jdbc:mysql://127.0.0.1:3306/dev_test?characterEncoding=utf8&useSSL=false&autoReconnect=false&rewriteBatchedStatements=true
    # mysql 8.0
    url: jdbc:mysql://127.0.0.1:3306/dev_test?characterEncoding=utf8&useSSL=false&autoReconnect=false&rewriteBatchedStatements=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
  jackson:
    default-property-inclusion: non_null

urule:
  repository:
    databasetype: mysql
    datasourcename: datasource

server:
  port: 8787
